clone:
  depth: full
pipelines:
  branches:
    master:
      - step:
          script:
            - git remote add sync git@github.com:tmedicci/esp-idf-libutils.git
            - git checkout master
            - git pull
            - git push sync master
